name: graficos_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  charts_flutter: ^0.12.0
  csv: ^5.1.1
  fl_chart: ^0.66.1
  flutter:
    sdk: flutter
  flutter_charts: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/datosGallo.csv
    - assets/datosGeneros.csv
  uses-material-design: true
  
